
spring:
    application:
        name: study_mq
    #MQ配置
    rabbitmq:
        host: 111.231.82.55
        port: 5672
        username: admin
        password: admin
        virtual-host: my_vhost

    activemq:
        broker-url: tcp://111.231.82.55:61616
        user: admin
        password: admin
        in-memory: true
        pool.enabled: false



server:
    port: 8080

